### ISSUE TITLE
Manifest error

### ISSUE THREAD

**Issue by Durandil67** [gitMenv/UEcastoc#12]
Error when creating manifest for .ucas/.utoc files:

> goroutine 17 [running, locked to thread]:
> main.ParseDependencies({0xc0004ba000, 0x40000, 0x42000})
>         C:/UEcastoc/manifest.go:233 +0x605
> main.(*UTocData).constructManifest(0xc00001d1e0?, {0xc0000fea50?, 0x2c?})
>         C:/UEcastoc/manifest.go:90 +0xe5
> main.createManifestFile(0x7ff80c447018?, 0xc000078000?, 0x0?, 0x1?)
>         C:/UEcastoc/dllAPI.go:137 +0x405

**Comment by nuadaxxx** [comment]
Why can i not unpack main.ucas/utoc all others work. ?

goroutine 17 [running, locked to thread]:
main.parseDirectoryIndex(0x7fff13b683a0?, 0x3)
        C:/UEcastoc/utoc.go:171 +0x7cd
main.parseUtocFile({0xc00012a9d8, 0x6}, {0x7fff13d108c0, 0x0, 0x0})
        C:/UEcastoc/utoc.go:327 +0xb09
main.createManifestFile(0x7fff137e7018?, 0xc000106000?, 0x0?, 0x1?)
        C:/UEcastoc/dllAPI.go:106 +0xd6

**Comment by Cyberim** [comment]
[wanted: dead]
the same problem

**Comment by gitMenv** [comment]
Which game are you trying to unpack? Is it the game files themselves, or is it a modified game? What command did you use that led to these errors? With that information, I can look into it a little bit better.

**Comment by nuadaxxx** [comment]
> Which game are you trying to unpack? Is it the game files themselves, or is it a modified game? What command did you use that led to these errors? With that information, I can look into it a little bit better.

Hogwarts Legacy --  Global.ucas / utoc files

command = main.exe manifest global.utoc global.ucas global.json

error says something about c: but program sit in d:

goroutine 17 [running, locked to thread]:
main.parseDirectoryIndex(0x7fff15b983a0?, 0x3)
        C:/UEcastoc/utoc.go:171 +0x7cd
main.parseUtocFile({0xc00000aac0, 0xb}, {0x7fff15d408c0, 0x0, 0x0})
        C:/UEcastoc/utoc.go:327 +0xb09
main.createManifestFile(0x7fff15817018?, 0xc000094000?, 0x0?, 0x1?)
        C:/UEcastoc/dllAPI.go:106 +0xd6

**Comment by nuadaxxx** [comment]
are you trying to fix it or what's the status?

**Comment by Mervius** [comment]
I also get
`panic: runtime error: index out of range [0] with length 0

goroutine 17 [running, locked to thread]:
main.ParseDependencies({0xc000824030, 0x2c, 0x30})
        C:/UEcastoc/manifest.go:233 +0x605
main.(*UTocData).constructManifest(0xc00008cf70?, {0xc0000aaa20?, 0x8?})
        C:/UEcastoc/manifest.go:90 +0xe5
main.createManifestFile(0x7fffdbad7018?, 0xc000086000?, 0x0?, 0x1?)
        C:/UEcastoc/dllAPI.go:137 +0x405`
for every file I try no matter what it is.

**Comment by gitMenv** [comment]
There are requirements on how to run the program. Have a look at the help text that is provided and ensure that you enter the commands as it is asked. I am trying to fix this by making the program in such a way that it doesn't require a manifest file anymore, but this all takes time, which I don't have a lot of. I am working on it and I will also create a tutorial on how to use the rudimentary tool once I get to that.

**Comment by Mervius** [comment]
I fixed it. The dll it generated was bad so i deleted it and a new one was made that worked.

**Comment by gitRuhi** [comment]
> I fixed it. The dll it generated was bad so i deleted it and a new one was made that worked.

Can u describe it more briefly?

**Comment by nuadaxxx** [comment]
> There are requirements on how to run the program. Have a look at the help text that is provided and ensure that you enter the commands as it is asked. I am trying to fix this by making the program in such a way that it doesn't require a manifest file anymore, but this all takes time, which I don't have a lot of. I am working on it and I will also create a tutorial on how to use the rudimentary tool once I get to that.

what is with the global.ucas/utoc it still doesn't work even with this not !

@pushd %~dp0
@if exist "output" goto 1
mkdir "output"
:1
@if exist "manifest" goto 2
mkdir "manifest"
:2
timeout -t 1 -nobreak
@if "%~1"=="" goto skip
.\main.exe unpackAll "%~dpn1.utoc" "%~dpn1.ucas" output\
.\main.exe manifest "%~dpn1.utoc" "%~dpn1.ucas" "manifest\%~n1.json"
:skip
